/* -------------------------------------------------------------------------- */
/*  Interface copy                                                             */
/*                                                                             */
/*  Everything a component says in its own voice: labels, headings, aria text.  */
/*  Editorial content (products, posts, policies) lives in site.js / legal.js   */
/*  and their .zh counterparts instead.                                        */
/*                                                                             */
/*  Keys are looked up with `t('nav.cta')`. A missing zh key falls back to the  */
/*  English string rather than rendering the key, so a half-finished            */
/*  translation degrades instead of breaking.                                   */
/*                                                                             */
/*  `{name}` style placeholders are filled by the second argument to `t`.       */
/* -------------------------------------------------------------------------- */

export const ui = {
  en: {
    locale: {
      label: 'Language',
      switchTo: 'Switch to Chinese',
      current: 'English',
    },
    common: {
      products: 'Products',
      industries: 'Industries',
      allIndustries: 'See all industries',
      exploreIndustry: 'Explore the {name} dashboard',
      blog: 'Blog',
      careers: 'Careers',
      contact: 'Contact',
      soon: 'Soon',
      walkthrough: 'Book a walkthrough',
      exploreProduct: 'Explore {name}',
      seeProducts: 'See the products',
      compareProducts: 'Compare the products',
      readRoadmap: 'Read the roadmap',
      joinBeta: 'Join the beta list',
      builtFor: 'Built for',
      contents: 'Contents',
      home: 'Home',
      logoHome: 'BIYY Tech home',
    },
    nav: {
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      panelLabel: 'Products',
      industriesPanelLabel: 'Industries',
      industriesPanelNote:
        'Same database underneath. The screen is laid out for the decisions your trade makes weekly.',
    },
    hero: {
      eyebrow: 'Dashboards and databases for SMEs',
      line1: 'Retire the',
      line2: 'spreadsheet.',
      line3: 'Keep the business.',
      body: 'BIYY Tech replaces the spreadsheets your business runs on with a real database and a dashboard built for your industry. One version of the truth, updating as work happens, live in two weeks.',
      sceneLabel: 'Show background {n}',
    },
    home: {
      productsEyebrow: 'Products',
      productsTitle: 'Three products, one account, one database underneath.',
      productsBody:
        'The dashboard and the database your business runs on, a website wired into the same data, and AI pointed at that data once there is something worth pointing it at.',
    },
    stats: {
      note: 'Figures reflect typical results reported by BIYY Tech pilot customers across retail, wholesale and service businesses. Your numbers will depend on your starting point. We will tell you what to expect during the walkthrough.',
    },
    pillars: {
      eyebrow: 'Why BIYY',
      title: 'Enterprise discipline, sized for a business that still knows every customer.',
      body: 'Most SME software is either a toy or a cut-down ERP. We build the middle: rigorous where it matters (schema design, audit trails, permissions) and ruthlessly simple everywhere else.',
    },
    industries: {
      eyebrow: 'Who runs on BIYY',
      title: 'Different floors. Same spreadsheet.',
      body: 'The dashboard changes by industry because the weekly decisions do. The file everyone is currently emailing each other does not.',
      carouselLabel: 'Industries served',
    },
    features: {
      eyebrow: 'Inside {name}',
      title: 'The four things your team will actually touch every day.',
    },
    testimonials: {
      eyebrow: 'From the floor',
      title: 'What changed after the second week.',
      carouselLabel: 'Customer stories',
    },
    comparison: {
      eyebrow: 'The honest comparison',
      title: 'Four ways to run operations. Here is where each one breaks.',
      headApproach: 'Approach',
      headCost: 'Cost',
      headSpeed: 'Time to value',
      headVerdict: 'Where it lands',
    },
    process: {
      eyebrow: 'Rollout',
      title: 'Two weeks. Four steps. No consultants living in your office.',
      body: 'Every step has an owner, a date and a definition of done before we start.',
      badge: 'days from walkthrough to every branch live',
    },
    faq: {
      eyebrow: 'Questions',
      title: 'The things people ask before they say yes.',
      body: 'If yours is not here, ask it on the walkthrough. We would rather answer it before you buy.',
    },
    cta: {
      title: 'Ready to stop rebuilding the same report every Monday?',
      body: 'Thirty minutes, your actual spreadsheets open, and a straight answer on whether BIYY is worth it for your business. No slide deck.',
    },
    carousel: {
      previous: 'Previous',
      next: 'Next',
      wraps: '{label} (wraps around)',
    },
    backToTop: 'Back to top',
    footer: {
      companyTitle: 'Company',
      resourcesTitle: 'Resources',
      whyYiy: 'Why BIYY',
      results: 'Results',
      rollout: 'How rollout works',
      faqLink: 'FAQ',
      support: 'Support',
      rights: '© {year} {legal}. All rights reserved.',
      privacy: 'Privacy',
      terms: 'Terms',
      cookies: 'Cookies',
      photography: 'Photography via Pexels',
    },
    consent: {
      dialogLabel: 'Cookie preferences',
      eyebrow: 'Cookies',
      body: 'This site sets no tracking cookies and loads no third-party scripts. We keep the choice below so that if we ever add analytics, it only runs for people who agreed. Declining changes nothing about what you can read here.',
      policyLink: 'Cookie policy',
      manage: 'Manage preferences',
      rejectAll: 'Reject all',
      acceptAll: 'Accept all',
      save: 'Save preferences',
      alwaysOn: 'Always on',
      preferencesButton: 'Cookie preferences',
      necessaryLabel: 'Strictly necessary',
      necessaryBody:
        'Serving the page and remembering this choice. Always on, and there is no switch for it because the site cannot work without it.',
      analyticsLabel: 'Analytics',
      analyticsBody:
        'Anonymous page and traffic statistics, so we can see which pages are worth writing more of. None are loaded today.',
      marketingLabel: 'Marketing',
      marketingBody:
        'Advertising and remarketing tags belonging to other companies. We do not run any, and we would rather keep it that way.',
    },
    chat: {
      dialogLabel: 'BIYY assistant',
      name: 'BIYY Bot',
      status: 'rule-based assistant',
      typing: 'typing…',
      open: 'Open the assistant',
      close: 'Close the assistant',
      nudge: 'Questions about dashboards, databases or migrating off spreadsheets? Ask me, no form required.',
      placeholder: 'Ask about dashboards, migration, pricing…',
      inputLabel: 'Message the assistant',
      send: 'Send',
    },
    contact: {
      eyebrow: 'Book a walkthrough',
      title: 'Thirty minutes. Your spreadsheets. A straight answer.',
      body: 'We will walk your floor or your front desk with your own files open, map what gets recorded and where it goes, and tell you whether BIYY is worth it for your business. If it is not, we will say so.',
      sentTitle: 'We opened a draft in your mail client.',
      sentBody:
        'Nothing has reached us yet. Press send on that draft and we will reply within one working day.',
      noDraftTitle: 'If no draft appeared',
      noDraftBody:
        'Some machines have no mail app configured. Copy the enquiry and send it from wherever you do read mail, to',
      copy: 'Copy the enquiry',
      copied: 'Copied',
      edit: 'Edit the enquiry',
      preamble:
        'Fields marked required are the ones we need to reply. Everything else helps us come prepared.',
      name: 'Name',
      namePlaceholder: 'Your name',
      business: 'Business',
      businessPlaceholder: 'Business name',
      email: 'Email',
      emailPlaceholder: 'you@business.com',
      phone: 'Phone / WhatsApp',
      phonePlaceholder: 'Optional',
      required: 'required',
      interest: 'Interested in',
      size: 'Size',
      message: 'What is costing you time right now?',
      messagePlaceholder: 'Rebuilding the weekly report, versions that disagree, month-end reporting…',
      submit: 'Send enquiry',
      disclaimer:
        'This opens a draft in your own mail client. Nothing is sent until you press send there. No newsletter, no drip sequence. We reply once, from a human.',
      oneError: 'One field still needs fixing before we can draft the enquiry.',
      manyErrors: '{n} fields still need fixing before we can draft the enquiry.',
      direct: 'Direct',
      coverTitle: 'What we will cover',
      roadmapSuffix: ' (roadmap)',
      interests: [
        'Dashboards & Databases',
        'Website & Integrations',
        'More than one',
        'Not sure yet',
      ],
      sizes: ['1 outlet', '2–5 outlets', '6–20 outlets', '20+ outlets'],
      errName: 'Tell us who you are.',
      errBusiness: 'Which business is this for?',
      errEmail: 'We need somewhere to reply.',
      errEmailFormat: 'That does not look like an email address.',
      errPhone: 'Leave this blank, or give a number we can actually dial.',
      mailSubject: 'Walkthrough request: {who}',
      mailName: 'Name',
      mailBusiness: 'Business',
      mailEmail: 'Email',
      mailPhone: 'Phone',
      mailInterest: 'Interested in',
      mailSize: 'Size',
      mailNoMessage: '(no message)',
    },
    careers: {
      eyebrow: 'Careers',
      title: 'Build the software that runs the shop.',
      body: 'A small team in {location}, replacing the spreadsheets small businesses depend on every trading day. If the phrase “which version is the right one” makes you want to fix something, we should talk.',
      valuesEyebrow: 'How we work',
      valuesTitle: 'Four things we actually hold each other to.',
      valuesBody:
        'Not posters. These are the arguments we have in code review and on customer calls.',
      rolesEyebrow: 'Open roles',
      rolesTitle: 'No vacancies open right now.',
      apply: 'Apply',
      noRoles:
        'We are not hiring at the moment. When a seat opens it will be listed here first, with the salary band, the location and what the first ninety days actually look like.',
      speculativeBefore: 'If you think you should be here anyway, send',
      // Follows an email link, so English carries its own leading space while
      // Chinese runs straight into its full stop. Same as blog.policyBodyAfter.
      speculativeAfter:
        ' one paragraph on something you built and why it was hard. We read all of them, and we keep the good ones on file.',
      notifyMe: 'Tell me when a role opens',
      speculativeSubject: 'Speculative application',
      applicationSubject: 'Application: {role}',
      teamAlt: 'The BIYY Tech team at work',
      perks: [
        {
          title: 'Four-day onboarding',
          body: 'Your first four days are spent in customer warehouses and at front desks, not in a wiki.',
        },
        {
          title: 'Ship in week one',
          body: 'Everyone merges something a customer touches inside their first week.',
        },
        {
          title: 'Hardware you choose',
          body: 'Pick the machine and the phone. We buy the cheap Android too, because customers use those.',
        },
        {
          title: 'Honest hours',
          body: 'No launch-week heroics. Rollouts are planned so nobody has to sleep under a desk.',
        },
      ],
    },
    /* The /industries index and the per-industry pages under it. `industries`
       above is the homepage carousel; this is the section that owns the
       standalone pages. */
    industryIndex: {
      eyebrow: 'Industries',
      title: 'Twelve floors we have already built the layout for.',
      body: 'The database is the same underneath. What changes is the first screen, because a distributor, a clinic and a barbershop do not make the same decision on a Monday. Pick the one you recognise.',
      cardCta: 'See the dashboard',
      notListed: 'Not on this list?',
      notListedBody:
        'We build the layout from what you decide every week, so an industry we have not written a page for is a walkthrough rather than a no. Tell us the trade and the three numbers you check most, and we will tell you honestly whether we are the right people.',
    },
    industry: {
      eyebrow: 'Industries',
      painsEyebrow: 'What it replaces',
      painsTitle: 'The way this usually works today.',
      painsBody:
        'Written from walkthroughs rather than from a persona document. If none of these are true for you, say so on the call and we will stop wasting your afternoon.',
      panelsEyebrow: 'The first screen',
      panelsTitle: 'What the dashboard opens on.',
      panelsBody:
        'Every panel is attached to a decision somebody makes on a known rhythm. Anything that only restates what you already knew does not ship.',
      crossEyebrow: 'Other floors',
      crossTitle: 'Same method, different first screen.',
      faqEyebrow: 'Questions',
      faqTitle: 'Asked on every one of these calls.',
      faqBody: 'If yours is not here, ask it on the walkthrough. We would rather answer before you commit.',
      heroAlt: 'A {name} business at work',
    },
    /* Section copy for the extra blocks in ProductExtras. Each product that
       carries those blocks names its own namespace through `extrasKey` in
       site.js, because the same table means different things on a website
       build and on a database build. `web` is the default. */
    dash: {
      valueEyebrow: 'What it is worth',
      valueTitle: 'What changes in the working week.',
      valueBody:
        'Not features. What is different once the data lives in one place and the screen is already correct when somebody opens it.',
      limitsEyebrow: 'The limits',
      limitsTitle: 'What we do not do.',
      limitsBody: 'Better said here than discovered in month two.',
      faqEyebrow: 'Questions',
      faqTitle: 'Asked on every one of these calls.',
      faqBody:
        'If yours is not here, ask it on the walkthrough. We would rather answer before you commit.',
      bandAlt: 'An operations dashboard open on a laptop in a back office',
    },
    web: {
      bandAlt: 'A product being photographed for an online listing beside a laptop',
      valueEyebrow: 'What it is worth',
      valueTitle: 'What a new site actually changes for the business.',
      valueBody:
        'Not impressions and bounce rate. What is different on the floor once the site and the system behind it are the same system.',
      connectEyebrow: 'The wiring',
      connectTitle: 'What the site reads, and what it writes back.',
      connectBody:
        'This is the half a web studio cannot do and a software vendor will not. Every surface below is one account away, not a spreadsheet somebody exports on Friday.',
      headSurface: 'Surface',
      headReads: 'Reads from BIYY',
      headWrites: 'Writes back to BIYY',
      none: '—',
      platformsEyebrow: 'Already have a site',
      platformsTitle: 'If yours is worth keeping, we wire it instead of rebuilding it.',
      platformsBody:
        'Most of this work is a new build. When a site is genuinely sound we integrate with the one you have and quote less, and how deep that can go is decided by what it was built on rather than by what you spend.',
      stagesEyebrow: 'How the build runs',
      stagesTitle: 'Three weeks, four stages, one staging link you can share.',
      stagesBody: 'Every stage has an owner and something you can look at by the end of it.',
      limitsEyebrow: 'The limits',
      limitsTitle: 'What we do not do.',
      limitsBody: 'Better said here than discovered in month two.',
      faqEyebrow: 'Questions',
      faqTitle: 'Asked on every one of these calls.',
      faqBody: 'If yours is not here, ask it on the walkthrough. We would rather answer before you commit.',
    },
    ai: {
      bandAlt: 'A back office where the records the model reads are entered',
      valueEyebrow: 'What it is worth',
      valueTitle: 'What changes once the answer costs a sentence.',
      valueBody:
        'Not model names and parameter counts. What is different in the week once the repetitive half of the work is drafted, checked and routed before anyone opens it.',
      connectEyebrow: 'The boundary',
      connectTitle: 'What the model may read, and what it is allowed to write.',
      connectBody:
        'The first question on every one of these calls, answered here rather than in an agreement three weeks later. Reads follow the permissions your team already has; nothing in the write column reaches a record without clearing its confidence threshold.',
      headSurface: 'Surface',
      headReads: 'Reads from BIYY',
      headWrites: 'Writes back to BIYY',
      none: '—',
      stagesEyebrow: 'How the build runs',
      stagesTitle: 'Four weeks, and it goes live checking before it goes live committing.',
      stagesBody:
        'Every stage has an owner, and the one in the middle exists so the thing is measured against known answers before anybody relies on it.',
      limitsEyebrow: 'The limits',
      limitsTitle: 'What we do not do.',
      limitsBody: 'Better said here than discovered in month two.',
      faqEyebrow: 'Questions',
      faqTitle: 'Asked on every one of these calls.',
      faqBody:
        'If yours is not here, ask it on the walkthrough. We would rather answer before you commit.',
    },
    blog: {
      eyebrow: 'Blog',
      title: 'Field notes from the floor.',
      body: 'What we learn moving businesses off spreadsheets when they cannot afford a bad week. Databases, dashboards, pricing, and the things that go wrong before they go right.',
      readPiece: 'Read the piece',
      moreWriting: 'More writing',
      policyTitle: 'How we write this',
      policyBody:
        'Posts are written by the people who do the work, not by a content team. Every one states who wrote it, what qualifies them, when it was last reviewed and where the numbers came from, including the limits of the sample. If you find an error, write to',
      // Follows an email link with no space of its own: English needs one in
      // front, Chinese runs straight into its comma.
      policyBodyAfter: ' and we will correct it and note the change.',
    },
    post: {
      shortAnswer: 'The short answer',
      takeaways: 'Key takeaways',
      aboutAuthor: 'About the author',
      reviewedBy: 'Reviewed by {name}, {role}.',
      faqHeading: 'Frequently asked questions',
      sources: 'Sources',
      keepReading: 'Keep reading',
      published: 'Published',
      reviewed: 'Reviewed',
      readTime: '{time} read',
      correctionsBefore: 'Spotted something wrong? Write to',
    },
    product: {
      whatEyebrow: 'What you get',
      whatTitle: 'Everything {name} does on day one.',
      whatBody:
        'Built for {audience}, configured to your outlets, roles and approval rules during onboarding.',
      seeAll: 'See all products',
      crossEyebrow: 'Also from BIYY',
      crossTitle: 'The rest of the operations layer.',
      heroAlt: '{name} in a working environment',
      inUseAlt: '{name} in use',
    },
    legal: {
      askUs: 'Ask us',
      lastUpdated: 'Last updated',
    },
    notFound: {
      title: 'That page is not on the shelf.',
      body: 'The link is broken or the page moved. Head back to the products, or tell us what you were looking for.',
      home: 'Back to home',
      contact: 'Contact us',
    },
  },

  zh: {
    locale: {
      label: '语言',
      switchTo: '切换到英文',
      current: '中文',
    },
    common: {
      products: '产品',
      industries: '行业',
      allIndustries: '查看所有行业',
      exploreIndustry: '了解{name}仪表板',
      blog: '博客',
      careers: '招聘',
      contact: '联系我们',
      soon: '即将',
      walkthrough: '预约实地走访',
      exploreProduct: '了解{name}',
      seeProducts: '查看产品',
      compareProducts: '比较各个产品',
      readRoadmap: '查看路线图',
      joinBeta: '加入内测名单',
      builtFor: '为谁而建',
      contents: '目录',
      home: '首页',
      logoHome: 'BIYY Tech 首页',
    },
    nav: {
      openMenu: '打开菜单',
      closeMenu: '关闭菜单',
      panelLabel: '产品',
      industriesPanelLabel: '行业',
      industriesPanelNote: '底下是同一个数据库。变的是屏幕的排布，按你这一行每周要做的决定来排。',
    },
    hero: {
      eyebrow: '为中小企业做的仪表板与数据库',
      line1: '让表格退休，',
      line2: '生意',
      line3: '照常运转。',
      body: 'BIYY Tech 把你生意赖以运转的那些表格，换成一个真正的数据库，加一块为你的行业做的仪表板。只有一份真数，随着工作发生而更新，两周上线。',
      sceneLabel: '显示第 {n} 个背景',
    },
    home: {
      productsEyebrow: '产品',
      productsTitle: '三个产品，一个账户，底下是同一个数据库。',
      productsBody:
        '你的生意每天要看的那块仪表板和它底下的数据库，一个接进同一批数据的网站，以及当这批数据真的值得被指着看时，指过去的 AI。',
    },
    stats: {
      note: '这些数字反映 BIYY Tech 试点客户在零售、批发与服务行业中报告的典型结果。你的数字取决于你的起点。我们会在走访时告诉你该期待什么。',
    },
    pillars: {
      eyebrow: '为什么选 BIYY',
      title: '大企业级的严谨，尺寸却适合一家还认得每位客户的公司。',
      body: '多数中小企业软件不是玩具，就是删减版 ERP。我们做中间那一档：在重要的地方严谨（表结构设计、审计轨迹、权限），在其余所有地方简单到底。',
    },
    industries: {
      eyebrow: '谁在用 BIYY',
      title: '不同的场地，同一张表格。',
      body: '仪表板因行业而不同，因为每周要做的决定不同。而大家现在互相转发的那个文件，各行各业都一样。',
      carouselLabel: '服务的行业',
    },
    features: {
      eyebrow: '走进{name}',
      title: '你的团队每天真正会碰的四件事。',
    },
    testimonials: {
      eyebrow: '来自一线',
      title: '第二周之后，发生了什么变化。',
      carouselLabel: '客户故事',
    },
    comparison: {
      eyebrow: '一次诚实的比较',
      title: '四种跑运营的方式。这是每一种崩掉的地方。',
      headApproach: '做法',
      headCost: '成本',
      headSpeed: '见效时间',
      headVerdict: '最后落在哪里',
    },
    process: {
      eyebrow: '实施',
      title: '两周。四步。没有常驻你办公室的顾问。',
      body: '开始之前，每一步都有负责人、有日期，也有明确的完成标准。',
      badge: '天，从走访到每家分店上线',
    },
    faq: {
      eyebrow: '常见问题',
      title: '大家在点头之前会问的那些事。',
      body: '如果这里没有你的问题，走访时问出来。我们宁愿在你付钱之前就回答。',
    },
    cta: {
      title: '准备好不用每个周一都重做同一张报表了吗？',
      body: '三十分钟，把你真实的表格打开，直接告诉你 BIYY 对你的生意值不值。没有幻灯片。',
    },
    carousel: {
      previous: '上一个',
      next: '下一个',
      wraps: '{label}（会循环回到开头）',
    },
    backToTop: '回到顶部',
    footer: {
      companyTitle: '公司',
      resourcesTitle: '资源',
      whyYiy: '为什么选 BIYY',
      results: '成效',
      rollout: '实施流程',
      faqLink: '常见问题',
      support: '支持',
      rights: '© {year} {legal}。保留所有权利。',
      privacy: '隐私',
      terms: '条款',
      cookies: 'Cookie',
      photography: '图片来自 Pexels',
    },
    consent: {
      dialogLabel: 'Cookie 偏好',
      eyebrow: 'Cookie',
      body: '本站不设跟踪 cookie，也不加载第三方脚本。我们保留下面这个选择，是为了万一将来加入分析工具，它只会对同意过的人运行。拒绝不会改变你在这里能读到的任何内容。',
      policyLink: 'Cookie 政策',
      manage: '管理偏好',
      rejectAll: '全部拒绝',
      acceptAll: '全部接受',
      save: '保存偏好',
      alwaysOn: '始终开启',
      preferencesButton: 'Cookie 偏好',
      necessaryLabel: '严格必要',
      necessaryBody:
        '用于提供页面并记住这个选择。始终开启，也没有开关，因为网站离了它无法工作。',
      analyticsLabel: '分析',
      analyticsBody:
        '匿名的页面与流量统计，让我们知道哪些页面值得多写。今天一个都没有加载。',
      marketingLabel: '营销',
      marketingBody:
        '属于其他公司的广告与再营销代码。我们一个都不跑，也希望一直这样。',
    },
    chat: {
      dialogLabel: 'BIYY 助手',
      name: 'BIYY 小助手',
      status: '基于规则的助手',
      typing: '正在输入…',
      open: '打开助手',
      close: '关闭助手',
      nudge: '关于仪表板、数据库，或者怎么离开表格有疑问？直接问我，不用填表。',
      placeholder: '问问仪表板、数据迁移或价格…',
      inputLabel: '给助手发消息',
      send: '发送',
    },
    contact: {
      eyebrow: '预约实地走访',
      title: '三十分钟。你的表格。一个直接的答案。',
      body: '我们会带着你自己的文件走一遍你的卖场或前台，把「什么被记下来、之后去了哪里」画出来，然后告诉你 BIYY 对你的生意值不值。如果不值，我们会直说。',
      sentTitle: '我们已经在你的邮件客户端里打开了一封草稿。',
      sentBody: '目前还没有任何东西到达我们这里。在那封草稿上按发送，我们会在一个工作日内回复。',
      noDraftTitle: '如果没有出现草稿',
      noDraftBody:
        '有些电脑没有配置邮件应用。把这条询问复制下来，从你平常收邮件的地方发送到',
      copy: '复制这条询问',
      copied: '已复制',
      edit: '修改这条询问',
      preamble: '标注为必填的字段是我们回复所需要的。其余的能帮我们提前做好准备。',
      name: '姓名',
      namePlaceholder: '你的姓名',
      business: '企业',
      businessPlaceholder: '企业名称',
      email: '邮箱',
      emailPlaceholder: 'you@business.com',
      phone: '电话 / WhatsApp',
      phonePlaceholder: '选填',
      required: '必填',
      interest: '感兴趣的产品',
      size: '规模',
      message: '现在什么最花你的时间？',
      messagePlaceholder: '每周重做报表、几个版本对不上、月底报表…',
      submit: '发送询问',
      disclaimer:
        '这会在你自己的邮件客户端里打开一封草稿。在你按下发送之前什么都不会寄出。没有新闻邮件，没有培育序列。我们由真人回复一次。',
      oneError: '还有一个字段需要修正，我们才能生成这条询问。',
      manyErrors: '还有 {n} 个字段需要修正，我们才能生成这条询问。',
      direct: '直接联系',
      coverTitle: '走访会聊什么',
      roadmapSuffix: '（路线图）',
      interests: ['仪表板与数据库', '网站与集成', '不止一个', '还不确定'],
      sizes: ['1 家门店', '2 至 5 家门店', '6 至 20 家门店', '20 家以上'],
      errName: '告诉我们你是谁。',
      errBusiness: '这是为哪家企业问的？',
      errEmail: '我们需要一个能回复的地方。',
      errEmailFormat: '这看起来不像一个邮箱地址。',
      errPhone: '要么留空，要么给一个真的打得通的号码。',
      mailSubject: '走访申请：{who}',
      mailName: '姓名',
      mailBusiness: '企业',
      mailEmail: '邮箱',
      mailPhone: '电话',
      mailInterest: '感兴趣的产品',
      mailSize: '规模',
      mailNoMessage: '（没有留言）',
    },
    careers: {
      eyebrow: '招聘',
      title: '做那套让店真正跑起来的软件。',
      body: '一支在{location}的小团队，替换掉小企业每个营业日都要依赖的那些表格。如果「到底哪个版本才是对的」这句话让你想动手修点什么，我们该聊聊。',
      valuesEyebrow: '我们怎么工作',
      valuesTitle: '我们真的会互相要求的四件事。',
      valuesBody: '不是墙上的标语。这些是我们在代码评审和客户电话里真的会争的东西。',
      rolesEyebrow: '开放职位',
      rolesTitle: '目前没有空缺。',
      apply: '申请',
      noRoles:
        '我们目前不招人。一旦有位置空出来，会先发布在这里，附上薪资区间、地点，以及头九十天实际上是什么样。',
      speculativeBefore: '如果你觉得自己无论如何都该在这里，写一段你做过的东西、以及它为什么难，发到',
      speculativeAfter: '。我们每一封都读，好的会存档。',
      notifyMe: '有职位时通知我',
      speculativeSubject: '自荐申请',
      applicationSubject: '应聘：{role}',
      teamAlt: '工作中的 BIYY Tech 团队',
      perks: [
        {
          title: '四天入职',
          body: '你的头四天在客户的仓库和前台度过，而不是在一份 wiki 里。',
        },
        {
          title: '第一周就交付',
          body: '每个人都在第一周内合并一样客户会碰到的东西。',
        },
        {
          title: '设备你自己挑',
          body: '电脑和手机你选。我们也会买便宜的安卓机，因为客户用的就是那些。',
        },
        {
          title: '诚实的工时',
          body: '没有上线周的英雄主义。实施的排期是让没有人需要睡在桌子底下。',
        },
      ],
    },
    industryIndex: {
      eyebrow: '行业',
      title: '十二种场地，布局我们已经做过了。',
      body: '底下的数据库是同一个。变的是第一屏，因为分销商、诊所和理发店在周一要做的决定不一样。挑一个你认得的。',
      cardCta: '看这块仪表板',
      notListed: '名单上没有你这一行？',
      notListedBody:
        '我们是按「你每周要决定什么」来做布局的，所以一个我们还没写页面的行业，意味着一次走访，而不是一句拒绝。告诉我们你做哪一行、最常看的三个数字是什么，我们会诚实地告诉你我们是不是合适的人。',
    },
    industry: {
      eyebrow: '行业',
      painsEyebrow: '它取代了什么',
      painsTitle: '这件事今天通常是怎么办的。',
      painsBody: '写自真实走访，不是写自一份用户画像文档。如果这些对你一条都不成立，在电话里直说，我们就不浪费你一个下午。',
      panelsEyebrow: '第一屏',
      panelsTitle: '这块仪表板打开时是什么。',
      panelsBody: '每一块面板都挂在某个人按固定节奏做的决定上。任何只是重述你早就知道的东西，都不会上线。',
      crossEyebrow: '其他场地',
      crossTitle: '同一套方法，不同的第一屏。',
      faqEyebrow: '常见问题',
      faqTitle: '这类电话里每次都会问到的。',
      faqBody: '这里没有你的问题，就在走访时问出来。我们宁愿在你决定之前回答。',
      heroAlt: '工作中的{name}',
    },
    dash: {
      valueEyebrow: '它值在哪里',
      valueTitle: '一周的工作里，到底有什么变了。',
      valueBody: '不是功能清单，而是当数据只待在一个地方、屏幕在有人打开时就已经是对的之后，实际发生的变化。',
      limitsEyebrow: '边界',
      limitsTitle: '我们不做什么。',
      limitsBody: '写在这里，好过第二个月才发现。',
      faqEyebrow: '常见问题',
      faqTitle: '这类电话里每次都会问到的。',
      faqBody: '这里没有你的问题，就在走访时问出来。我们宁愿在你决定之前回答。',
      bandAlt: '后台办公室里笔记本电脑上打开的运营仪表板',
    },
    web: {
      bandAlt: '在笔记本电脑旁给商品拍照，准备上架',
      valueEyebrow: '它值在哪里',
      valueTitle: '一个新网站到底给这门生意带来什么改变。',
      valueBody: '不是曝光量和跳出率，而是当网站和它背后的系统合成一套之后，店里实际发生的变化。',
      connectEyebrow: '接线',
      connectTitle: '网站读什么，又写回去什么。',
      connectBody:
        '这一半，网页工作室做不了，软件供应商不愿做。下面每一个位置都只隔着一个账户，而不是谁在周五导出的一张表。',
      headSurface: '位置',
      headReads: '从 BIYY 读取',
      headWrites: '写回 BIYY',
      none: '—',
      platformsEyebrow: '已经有网站',
      platformsTitle: '如果你现在的站值得留，我们就接上去，而不是重做。',
      platformsBody:
        '这类项目多数是从头做一个新站。只有当现有网站确实没问题时，我们才直接接上去，报价也更低；能接多深取决于它是用什么做的，而不是你花了多少钱。',
      stagesEyebrow: '建站怎么推进',
      stagesTitle: '三周，四个阶段，一个可以随便转发的预览链接。',
      stagesBody: '每个阶段都有负责人，结束时都有你可以亲眼看的东西。',
      limitsEyebrow: '边界',
      limitsTitle: '我们不做什么。',
      limitsBody: '写在这里，好过第二个月才发现。',
      faqEyebrow: '常见问题',
      faqTitle: '这类电话里每次都会问到的。',
      faqBody: '这里没有你的问题，就在走访时问出来。我们宁愿在你决定之前回答。',
    },
    ai: {
      bandAlt: '后台办公室，模型要读的那些记录就是在这里被录进去的',
      valueEyebrow: '它值在哪里',
      valueTitle: '当一个答案只值一句话之后，什么变了。',
      valueBody: '不是模型的名字和参数量，而是当重复的那一半工作在有人打开之前就已经拟好、核过、分派好之后，这一周里实际发生的变化。',
      connectEyebrow: '边界在哪里',
      connectTitle: '模型能读什么，又被允许写什么。',
      connectBody:
        '这是这类电话里的第一个问题，与其三周后写进协议，不如现在就写在这里。读，按你团队本来就有的权限走；写这一列里的任何东西，不过置信阈值就到不了记录上。',
      headSurface: '位置',
      headReads: '从 BIYY 读取',
      headWrites: '写回 BIYY',
      none: '—',
      stagesEyebrow: '项目怎么推进',
      stagesTitle: '四周；先上线做核对，再上线做提交。',
      stagesBody: '每个阶段都有负责人，中间那个阶段的存在，就是为了在任何人依赖它之前，拿已知答案把它量出来。',
      limitsEyebrow: '边界',
      limitsTitle: '我们不做什么。',
      limitsBody: '写在这里，好过第二个月才发现。',
      faqEyebrow: '常见问题',
      faqTitle: '这类电话里每次都会问到的。',
      faqBody: '这里没有你的问题，就在走访时问出来。我们宁愿在你决定之前回答。',
    },
    blog: {
      eyebrow: '博客',
      title: '来自一线的现场笔记。',
      body: '把那些经不起一个坏星期的企业从表格里搬出来时，我们学到的东西。数据库、仪表板、定价，以及在做对之前会出的那些错。',
      readPiece: '阅读全文',
      moreWriting: '更多文章',
      policyTitle: '我们怎么写这些',
      policyBody:
        '文章由真正做这件事的人写，不是内容团队。每一篇都会说明是谁写的、他凭什么写、最后一次复核是什么时候，以及数字从哪里来，包括样本的局限。如果你发现错误，请写信到',
      policyBodyAfter: '，我们会更正并注明改动。',
    },
    post: {
      shortAnswer: '简短的答案',
      takeaways: '要点',
      aboutAuthor: '关于作者',
      reviewedBy: '由 {name}（{role}）复核。',
      faqHeading: '常见问题',
      sources: '资料来源',
      keepReading: '继续读',
      published: '发布于',
      reviewed: '复核于',
      readTime: '阅读约 {time}',
      correctionsBefore: '发现哪里不对？请写信到',
    },
    product: {
      whatEyebrow: '你会得到什么',
      whatTitle: '{name}在第一天就能做的一切。',
      whatBody: '为{audience}打造，在导入期间按你的门店、角色与审批规则完成配置。',
      seeAll: '查看所有产品',
      crossEyebrow: 'BIYY 的其他产品',
      crossTitle: '运营底座的其余部分。',
      heroAlt: '工作环境中的{name}',
      inUseAlt: '使用中的{name}',
    },
    legal: {
      askUs: '问我们',
      lastUpdated: '最后更新',
    },
    notFound: {
      title: '这个页面不在架上。',
      body: '链接失效了，或者页面已经搬走。回去看看产品，或者告诉我们你在找什么。',
      home: '回到首页',
      contact: '联系我们',
    },
  },
};
